import { notFound } from "next/navigation";
import { Building2, CalendarDays, PackageOpen, Plus, UtensilsCrossed } from "lucide-react";
import { AppShell } from "@/components/ui/app-shell";
import { Alert, Button, Card, EmptyState, ErrorState, LoadingState, PageHeader, SelectField, StatusBadge, TextAreaField, TextField, uiStyles } from "@/components/ui/primitives";

export default function DesignSystemPage(){
  if(process.env.NODE_ENV!=="development")notFound();
  const navigation=[{href:"/design-system",label:"Foundation",icon:Building2},{href:"/admin",label:"Example route",icon:CalendarDays}];
  return <AppShell workspace="Design system" fullName="Internal preview" roleLabel="Development only" currentPath="/design-system" navigation={navigation}>
    <PageHeader eyebrow="Aamish foundation" title="Calm food operations" description="Shared components are reviewed here before feature pages compose them." actions={<><Button variant="secondary">Secondary action</Button><Button><Plus size={17}/>Primary action</Button></>}/>
    <div className={uiStyles.referenceSection}><h2>Actions and status</h2><Card><div className={uiStyles.referenceStack}><Button size="small">Small</Button><Button>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="quiet">Quiet</Button><Button variant="danger">Danger</Button><Button loading loadingLabel="Publishing…">Publish</Button><Button disabled>Disabled</Button></div><div className={uiStyles.referenceStack} style={{marginTop:16}}><StatusBadge>Draft</StatusBadge><StatusBadge tone="success">Confirmed</StatusBadge><StatusBadge tone="warning">Cutoff soon</StatusBadge><StatusBadge tone="dangerTone">Needs attention</StatusBadge><StatusBadge tone="info">Transcribing</StatusBadge></div></Card></div>
    <div className={uiStyles.referenceSection}><h2>Fields</h2><Card><form className={uiStyles.referenceForm}><TextField label="Enterprise name" name="enterpriseName" required placeholder="e.g. Live Technologies" description="The client company shown throughout Aamish."/><SelectField label="Delivery location" name="location" required defaultValue=""><option value="" disabled>Select a location</option><option>Notun Bazar office with an intentionally long location name</option></SelectField><TextAreaField label="Internal note" name="note" placeholder="Add relevant context"/><TextField label="Corporate email" name="email" type="email" defaultValue="not-an-email" error="Enter a valid corporate email address."/><Button type="button">Save details</Button></form></Card></div>
    <div className={uiStyles.referenceSection}><h2>System feedback</h2><div className={uiStyles.referenceGrid}><Alert tone="info" title="Menu is still a draft">Publish it before scheduling a meal service.</Alert><Alert tone="success" title="Enterprise created">The administrator account is ready.</Alert><Alert tone="warning" title="Cutoff is approaching">Employees have 25 minutes to change their meal.</Alert><Alert tone="danger" title="Package could not be saved">Check the highlighted fields and try again.</Alert></div></div>
    <div className={uiStyles.referenceSection}><h2>Data states</h2><div className={uiStyles.referenceGrid}><EmptyState icon={<PackageOpen/>} title="No packages yet" description="Create a reusable meal package before publishing the service calendar." action={<Button><Plus size={17}/>Create package</Button>}/><LoadingState label="Loading meal services…"/><ErrorState description="We could not load the latest meal counts." requestId="demo-request-id" action={<Button variant="secondary">Try again</Button>}/><EmptyState icon={<UtensilsCrossed/>} title="Nothing needs attention" description="All current meal services are configured and ready for fulfillment."/></div></div>
  </AppShell>
}
